### ISSUE TITLE
Incomplete (thus invalid) Apache License

### ISSUE THREAD

**Issue by mehcode** [koute/libretro-backend#3]
The ([LICENSE-APACHE.txt](https://github.com/koute/libretro-backend/blob/master/LICENSE-APACHE.txt#L189) is legally invalid due to the template not being filled out. Just thought I'd point this out. Also we need a reference to the license on the [README](https://github.com/sfackler/rust-postgres-macros/issues/19).

**Comment by koute** [comment]
Fixed. Thanks!
