### ISSUE TITLE
retro_get_system_info only valid after retro_init

### ISSUE THREAD

**Issue by amfl** [koute/libretro-backend#4]
The `Retro::core_info` struct which `retro_get_system_info` reads from is incorrectly only populated after `retro_init` has been called.

This doesn't matter when starting Retroarch by passing the core and rom as command line arguments. However, if Retroarch 1.5.0 is started by itself and the core is selected from the "Load Core" GUI menu, `retro_get_system_info` is called before `retro_init` and returns empty strings for the core name and version. This results in some strange behavior:

- No core information is shown in the bottom left of the screen.
- Subsequently, attempting to load content with the core from the "Load Content" menu crashes Retroarch.

I am relatively new to both libretro and rust, so apologies if I have something wrong here. I arrived at the above conclusion due to:

- Changing the constructor values of `core_info` from empty strings to "foo", "bar". Under the circumstances above, this results in "1.5.0 - foo bar" showing up in the bottom left of Retroarch when the core is selected, which implies the values are not correctly overwritten in time by the core's implementation of `Backend::on_initialize`.
- Adding some `println!`s to libretro-backend which shows `retro_get_system_info` being called several times before `retro_init`

Experimentation was done with https://github.com/koute/pinky and with a minimal core of my own which uses libretro-backend.

**Comment by koute** [comment]
Oh, you're right! I totally missed that; even libretro docs say that it `Can be called at any time, even before retro_init().`

Thanks! I'll fix it right away.

**Comment by koute** [comment]
Fixed!
